# Generated by Django 5.1 on 2024-08-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='requeireTalla',
            new_name='requiereTalla',
        ),
    ]
