# Generated by Django 5.1 on 2024-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0003_producto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requeireTalla',
            field=models.BooleanField(default=True),
        ),
    ]
