# Generated by Django 5.1 on 2024-09-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0006_producto_fotouser1_producto_fotouser2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fotoUser1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoUser2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoUser3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoUser4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoUser5',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoUser6',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='requiereFotos',
        ),
    ]
