# Generated by Django 5.1 on 2024-09-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0007_remove_producto_fotouser1_remove_producto_fotouser2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamanyo1',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamanyo2',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamanyo3',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamanyo4',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
