# Generated by Django 5.1 on 2024-09-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0010_producto_modelo_producto_precio2_producto_precio3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
