# Generated by Django 5.1 on 2024-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0012_producto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto2',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='precio2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='precio3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='precio4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='requeireTalla',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='producto2',
            name='talla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='tamanyo1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='tamanyo2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='tamanyo3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='tamanyo4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto2',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
