# Generated by Django 5.1 on 2024-09-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0013_producto2_descripcion_producto2_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto2',
        ),
    ]
