# Generated by Django 5.1 on 2024-09-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0014_delete_producto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='productos'),
        ),
    ]
