# Generated by Django 5.1 on 2024-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorProductos', '0015_remove_producto_talla_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenEXTRA',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
