# Generated by Django 5.1 on 2024-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='fotoUser1',
            field=models.ImageField(blank=True, upload_to='fotosUsuarios'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fotoUser2',
            field=models.ImageField(blank=True, upload_to='fotosUsuarios'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fotoUser3',
            field=models.ImageField(blank=True, upload_to='fotosUsuarios'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fotoUser4',
            field=models.ImageField(blank=True, upload_to='fotosUsuarios'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fotoUser5',
            field=models.ImageField(blank=True, upload_to='fotosUsuarios'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fotoUser6',
            field=models.ImageField(blank=True, upload_to='fotosUsuarios'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='talla',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
