# Generated by Django 5.1 on 2024-09-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorPedidos', '0002_detallepedido_fotouser1_detallepedido_fotouser2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='comentarios_fotos',
            field=models.TextField(blank=True, help_text='Comentarios sobre las fotos'),
        ),
    ]
