# Generated by Django 5.1 on 2024-09-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creadorPedidos', '0003_detallepedido_comentarios_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='comentarios_fotos',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fotoUser1',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fotoUser2',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fotoUser3',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fotoUser4',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fotoUser5',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fotoUser6',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='talla',
        ),
    ]
