# Generated by Django 5.1 on 2024-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorPedidos', '0005_detallepedido_cpusuario_detallepedido_ciudadusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='talla',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
