# Generated by Django 5.1 on 2024-09-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creadorPedidos', '0006_detallepedido_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='modelo',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
